### ISSUE TITLE
Connecting XGO-mini with Raspberry Pi

### ISSUE THREAD

**Issue by gsheo** [Xgorobot/XGO-PythonLib#1]
I am trying to coding XGO-mini through Raspberry Pi for learning experience of python coding.
First I tried to follow what was on Youtube of Sentdex at below link.
https://www.youtube.com/watch?v=U2nNI9Yp_0g&list=RDCMUCfzlCWGWYyIQ0aLC5w48gBQ&index=5

Although I followed every step of the Youtube contents, the coded did not work although no error appeared on the code.
Therefore, I wonder something had changed at XGO-mini firmware after Sentdex had tried. It was Aug 23, 2021.

**Comment by jd3096-mpy** [comment]
We fix this
